<a href="https://colab.research.google.com/github/parikhdev/Google-Colaboratory/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [ ]:
print(torch.__version__)

2.10.0+cu128


In [ ]:
if torch.cuda.is_available():
  print("GPU is Available")
  print(f"GPU is {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not Available")

GPU is Available
GPU is Tesla T4


In [ ]:
torch.empty(2,3) # Show values already existing in the memories

tensor([[0.0000e+00, 4.4163e-41, 7.7052e+31],
        [7.2148e+22, 1.5766e-19, 1.0256e-08]])

In [ ]:
torch.zeros(2,3)
torch.ones(3,2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
torch.rand(2,3)

tensor([[0.7628, 0.8389, 0.8738],
        [0.1952, 0.2082, 0.0508]])

In [ ]:
torch.manual_seed(100) # same values everytime
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.tensor([[1,2,3], [2,4,6]])

tensor([[1, 2, 3],
        [2, 4, 6]])

In [ ]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [ ]:
torch.linspace(0,10, 10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [ ]:
torch.eye(5) # Identity Matrix

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
torch.full((3,5), 10)

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])

In [ ]:
x = torch.tensor([[1,2,3], [4,5,6], [6,7,8]])
x.shape # To see the shape

torch.Size([3, 3])

In [ ]:
torch.empty_like(x)

tensor([[106960491150049280,                427,               5994],
        [                 0, 120192546654650368,    281474976710656],
        [   135360457736825,                 81,         1095259632]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [ ]:
x.dtype # Check data type

torch.int64

In [ ]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32) # Float value to Int value

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype =torch.int32) # Int to Float value

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.rand_like(x, dtype= torch.float32) # Float to Int

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183]])

In [5]:
x = torch.randint(size = (2,3), low = 0, high = 10, dtype = torch.float32)

In [6]:
torch.abs(x)

tensor([[4., 7., 5.],
        [7., 9., 0.]])

In [7]:
torch.neg(x)

tensor([[-4., -7., -5.],
        [-7., -9., -0.]])

In [8]:
torch.round(x)

tensor([[4., 7., 5.],
        [7., 9., 0.]])

In [9]:
torch.ceil(x)

tensor([[4., 7., 5.],
        [7., 9., 0.]])

In [10]:
torch.floor(x)

tensor([[4., 7., 5.],
        [7., 9., 0.]])

In [11]:
torch.clamp(x, min=2,max=3)

tensor([[3., 3., 3.],
        [3., 3., 2.]])

In [12]:
e = torch.randint(size = (2,3), low = 0, high = 10, dtype = torch.float32)


In [13]:
torch.sum(e)

tensor(39.)

In [14]:
torch.sum(e, dim=0)

tensor([16., 13., 10.])

In [15]:
torch.sum(e, dim=1)

tensor([14., 25.])

In [16]:
torch.mean(e)

tensor(6.5000)

In [17]:
torch.min(e)

tensor(1.)

In [18]:
torch.max(e)

tensor(9.)

In [19]:
torch.median(e)

tensor(7.)

In [20]:
torch.std(e)

tensor(3.3317)

In [21]:
torch.prod(e)

tensor(20412.)

In [22]:
torch.var(e)

tensor(11.1000)

In [23]:
torch.argmax(e)

tensor(0)

In [24]:
torch.argmin(e)

tensor(2)

In [25]:
print(e)

tensor([[9., 4., 1.],
        [7., 9., 9.]])


In [28]:
f = torch.randint(size = (2,3), low = 0, high = 10, dtype = torch.float32)

In [32]:
a = torch.randint(size = (2,3), low = 0, high = 10, dtype = torch.float32)
b = torch.randint(size = (3,4), low = 0, high = 10, dtype = torch.float32)

In [33]:
torch.matmul(a,b)

tensor([[72., 45., 80., 11.],
        [70., 55., 96., 13.]])

In [34]:
c = torch.tensor([1,2,3])
d = torch.tensor([2,3,4])

In [37]:
torch.dot(c,d)

tensor(20)

In [42]:
torch.transpose(a, 0, 1)

tensor([[0., 4.],
        [9., 7.],
        [1., 1.]])

In [45]:
h = torch.randint(size = (3,3), low = 0, high = 10, dtype = torch.float32)

In [46]:
torch.det(h)

tensor(105.0000)

In [47]:
torch.inverse(h)

tensor([[-4.2857e-01,  1.4286e-01,  4.2857e-01],
        [ 5.5238e-01, -2.2857e-01, -3.5238e-01],
        [ 3.3333e-01, -3.8087e-09, -3.3333e-01]])

In [48]:
torch.log(h)

tensor([[2.0794, 1.6094, 1.6094],
        [1.9459,   -inf, 2.1972],
        [2.0794, 1.6094, 0.6931]])

In [50]:
torch.exp(h)

tensor([[2.9810e+03, 1.4841e+02, 1.4841e+02],
        [1.0966e+03, 1.0000e+00, 8.1031e+03],
        [2.9810e+03, 1.4841e+02, 7.3891e+00]])

In [51]:
torch.sqrt(h)

tensor([[2.8284, 2.2361, 2.2361],
        [2.6458, 0.0000, 3.0000],
        [2.8284, 2.2361, 1.4142]])

In [52]:
torch.sigmoid(h)

tensor([[0.9997, 0.9933, 0.9933],
        [0.9991, 0.5000, 0.9999],
        [0.9997, 0.9933, 0.8808]])

In [53]:
torch.relu(h)

tensor([[8., 5., 5.],
        [7., 0., 9.],
        [8., 5., 2.]])

In [54]:
torch.softmax(h, dim=0)

tensor([[4.2232e-01, 4.9832e-01, 1.7970e-02],
        [1.5536e-01, 3.3577e-03, 9.8114e-01],
        [4.2232e-01, 4.9832e-01, 8.9468e-04]])

In [58]:
i = torch.randint(size = (3,3), low = 0, high = 10, dtype = torch.float32)

In [59]:
h.add_(i)

tensor([[13., 12., 11.],
        [16.,  1., 13.],
        [ 9., 13.,  3.]])

In [60]:
h.subtract_(i)

tensor([[8., 5., 5.],
        [7., 0., 9.],
        [8., 5., 2.]])

In [61]:
i

tensor([[5., 7., 6.],
        [9., 1., 4.],
        [1., 8., 1.]])

In [62]:
h.relu_()

tensor([[8., 5., 5.],
        [7., 0., 9.],
        [8., 5., 2.]])

In [63]:
j = i.clone()

In [65]:
print(id(i))
id(j)

133840645039088


133840595773520

In [66]:
torch.cuda.is_available()

True

In [67]:
device = torch.device('cuda')

In [68]:
torch.rand((2,3), device = device)

tensor([[0.2232, 0.8623, 0.5888],
        [0.5195, 0.1802, 0.9209]], device='cuda:0')

In [69]:
i.to(device)

tensor([[5., 7., 6.],
        [9., 1., 4.],
        [1., 8., 1.]], device='cuda:0')

In [71]:
import time
a = time.time()
size = 10000
m = torch.randint(size = (size, size), low = 0, high = 100, dtype = torch.float32)
n = torch.randint(size = (size, size), low = 0, high = 100, dtype = torch.float32)
torch.matmul(m,n)
b = time.time()
cpu_time = a - b
print(cpu_time)

-17.87271523475647


In [72]:
c = time.time()
m = torch.randint(size = (size, size), low = 0, high = 100, dtype = torch.float32, device = device)
n = torch.randint(size = (size, size), low = 0, high = 100, dtype = torch.float32, device = device)
torch.matmul(m,n)
d = time.time()
gpu_time = c - d
print(gpu_time)

-0.1834712028503418


In [73]:
ratio = cpu_time/gpu_time
print(f"GPU is {ratio} times faster than CPU")

GPU is 97.41428059059119 times faster than CPU


In [76]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [77]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [78]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [79]:
b = torch.rand(2,3,4)
b

tensor([[[0.5856, 0.5695, 0.4082, 0.6459],
         [0.5528, 0.6401, 0.1127, 0.5399],
         [0.1406, 0.6083, 0.8463, 0.6324]],

        [[0.0521, 0.7733, 0.3984, 0.0106],
         [0.5000, 0.9627, 0.0764, 0.7897],
         [0.9773, 0.9103, 0.6529, 0.3756]]])

In [83]:
c = b.permute(2,0,1)
c
c.shape

torch.Size([4, 2, 3])

In [85]:
d = torch.rand(226,226,3)
d

tensor([[[0.7177, 0.2342, 0.8788],
         [0.7378, 0.7882, 0.1449],
         [0.7376, 0.7185, 0.5278],
         ...,
         [0.4160, 0.1064, 0.2419],
         [0.8859, 0.4090, 0.6644],
         [0.7116, 0.1053, 0.6396]],

        [[0.9542, 0.4962, 0.3221],
         [0.5718, 0.5771, 0.8736],
         [0.5793, 0.8924, 0.6774],
         ...,
         [0.6489, 0.6833, 0.0900],
         [0.2035, 0.7298, 0.5162],
         [0.9622, 0.5901, 0.3761]],

        [[0.1452, 0.5608, 0.4498],
         [0.7607, 0.2159, 0.1999],
         [0.6023, 0.2004, 0.1133],
         ...,
         [0.3497, 0.3533, 0.7542],
         [0.5788, 0.6783, 0.5312],
         [0.5594, 0.7949, 0.9595]],

        ...,

        [[0.8617, 0.3584, 0.7883],
         [0.9943, 0.5222, 0.7812],
         [0.9805, 0.1283, 0.4374],
         ...,
         [0.6491, 0.6161, 0.0511],
         [0.9189, 0.8059, 0.5703],
         [0.7338, 0.0489, 0.4455]],

        [[0.8063, 0.6348, 0.4147],
         [0.2811, 0.1336, 0.7766],
         [0.

In [86]:
d.unsqueeze(0)

tensor([[[[0.7177, 0.2342, 0.8788],
          [0.7378, 0.7882, 0.1449],
          [0.7376, 0.7185, 0.5278],
          ...,
          [0.4160, 0.1064, 0.2419],
          [0.8859, 0.4090, 0.6644],
          [0.7116, 0.1053, 0.6396]],

         [[0.9542, 0.4962, 0.3221],
          [0.5718, 0.5771, 0.8736],
          [0.5793, 0.8924, 0.6774],
          ...,
          [0.6489, 0.6833, 0.0900],
          [0.2035, 0.7298, 0.5162],
          [0.9622, 0.5901, 0.3761]],

         [[0.1452, 0.5608, 0.4498],
          [0.7607, 0.2159, 0.1999],
          [0.6023, 0.2004, 0.1133],
          ...,
          [0.3497, 0.3533, 0.7542],
          [0.5788, 0.6783, 0.5312],
          [0.5594, 0.7949, 0.9595]],

         ...,

         [[0.8617, 0.3584, 0.7883],
          [0.9943, 0.5222, 0.7812],
          [0.9805, 0.1283, 0.4374],
          ...,
          [0.6491, 0.6161, 0.0511],
          [0.9189, 0.8059, 0.5703],
          [0.7338, 0.0489, 0.4455]],

         [[0.8063, 0.6348, 0.4147],
          [0.2811

In [87]:
d.squeeze(0)

tensor([[[0.7177, 0.2342, 0.8788],
         [0.7378, 0.7882, 0.1449],
         [0.7376, 0.7185, 0.5278],
         ...,
         [0.4160, 0.1064, 0.2419],
         [0.8859, 0.4090, 0.6644],
         [0.7116, 0.1053, 0.6396]],

        [[0.9542, 0.4962, 0.3221],
         [0.5718, 0.5771, 0.8736],
         [0.5793, 0.8924, 0.6774],
         ...,
         [0.6489, 0.6833, 0.0900],
         [0.2035, 0.7298, 0.5162],
         [0.9622, 0.5901, 0.3761]],

        [[0.1452, 0.5608, 0.4498],
         [0.7607, 0.2159, 0.1999],
         [0.6023, 0.2004, 0.1133],
         ...,
         [0.3497, 0.3533, 0.7542],
         [0.5788, 0.6783, 0.5312],
         [0.5594, 0.7949, 0.9595]],

        ...,

        [[0.8617, 0.3584, 0.7883],
         [0.9943, 0.5222, 0.7812],
         [0.9805, 0.1283, 0.4374],
         ...,
         [0.6491, 0.6161, 0.0511],
         [0.9189, 0.8059, 0.5703],
         [0.7338, 0.0489, 0.4455]],

        [[0.8063, 0.6348, 0.4147],
         [0.2811, 0.1336, 0.7766],
         [0.

In [91]:
import numpy as np
a = torch.tensor([1,2,3,4])
a

tensor([1, 2, 3, 4])

In [92]:
b = a.numpy()
b

array([1, 2, 3, 4])

In [93]:
c = np.array([1,2,4,5])
c

array([1, 2, 4, 5])

In [94]:
torch.from_numpy(c)

tensor([1, 2, 4, 5])